### ISSUE TITLE
Datetime string

### ISSUE THREAD

**Issue by manh1208** [manh1208/SportsSocialNetwork#25]
Check toàn bộ những api nào trả về thời gian thì làm lại cho đúng format

**Comment by fanstatic2** [comment]
e tạo thêm 1 String cho mấy loại Datetime vs TimeSpan, tên như cũ + thêm "String".
Vd: CreateDate => CreateDateString.
CreateDate e vẫn để kiểu Datetime cho tiện mapping, ko thì hơi cực
