### ISSUE TITLE
Show Profile

### ISSUE THREAD

**Issue by manh1208** [manh1208/SportsSocialNetwork#49]
Followed trong cái api show profile để làm gì.
Cho a thêm 3 field về số người đang theo dõi mình và mình đang theo dõi bao nhiêu người, số bài đăng.
Cái Hobby thì thêm cái tên môn thể thao giúp a

**Comment by fanstatic2** [comment]
Followed là để khi mình vào xem profile của ng khác mình bik mình có follow nó chưa (Để hiện nút Follow hay Unfollow).
